"""empty message

Revision ID: 133961c8d6e7
Revises: 90d6ce36cf60
Create Date: 2022-05-02 17:31:42.085448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '133961c8d6e7'
down_revision = '90d6ce36cf60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'characters_list',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('characters_list', table_name='characters')
    op.drop_index('characters_list_2', table_name='characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('characters_list_2', 'characters', ['characters_list'], unique=False)
    op.create_index('characters_list', 'characters', ['characters_list'], unique=False)
    op.alter_column('characters', 'characters_list',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
