"""empty message

Revision ID: 2e088a172b95
Revises: 133961c8d6e7
Create Date: 2022-05-02 18:05:39.481055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e088a172b95'
down_revision = '133961c8d6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_name', table_name='favourites')
    op.drop_index('user_name_2', table_name='favourites')
    op.drop_table('favourites')
    op.drop_table('characters')
    op.drop_index('character_name', table_name='one_character')
    op.drop_index('character_name_2', table_name='one_character')
    op.drop_index('character_props', table_name='one_character')
    op.drop_index('character_props_2', table_name='one_character')
    op.drop_table('one_character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_character',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('character_props', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('character_props_2', 'one_character', ['character_props'], unique=False)
    op.create_index('character_props', 'one_character', ['character_props'], unique=False)
    op.create_index('character_name_2', 'one_character', ['character_name'], unique=False)
    op.create_index('character_name', 'one_character', ['character_name'], unique=False)
    op.create_table('characters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('characters_list', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('favourites',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_name_2', 'favourites', ['user_name'], unique=False)
    op.create_index('user_name', 'favourites', ['user_name'], unique=False)
    # ### end Alembic commands ###
